name: Update-Aliases

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true
    - name: Get Updated Aliases
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          Set-Location $GITHUB_WORKSPACE
          Write-Host "$GITHUB_WORKSPACE"
          dir
          ./src/Get-ResourceAliases.ps1
        azPSVersion: latest
    - name: Commit changes
      run: |
        cd $GITHUB_WORKSPACE
        now=$(date)
        git add --all
        git commit -a -m "auto update aliases $now"
        git push
